behaviors:
  tsp5-40:
    trainer_type: ppo
    hyperparameters:
      batch_size: 386
      buffer_size: 15440
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.925
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 200000000
    time_horizon: 256
    summary_freq: 10000